name: deploy

on:
  push:

env:
  DRY_RUN: ${{ github.ref != 'refs/heads/main' }}
  SSH_KEY: /data/ssh.key
  TERRAVARS: /data/terraform.tfvars.json
  TF_PLUGIN_CACHE_DIR: /data/plugin-cache
  KUBECONFIG: /data/kube.config.yml
  KUBE_CONFIG_PATH: /data/kube.config.yml
  ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
  TERRAFORM_VERSION: 1.1.9 # renovate: datasource=terraform-provider depName=terraform

jobs:
  terra:
    runs-on: [ubuntu-latest]
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      
